name: Supabase Migration

on:
  workflow_dispatch:

jobs:
  migration:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Supabase Setup
        uses: supabase/setup-cli@v1

      - name: Supabase Link
        run: supabase link --project-ref ${{ env.SUPABASE_PROJECT_ID }}

      - name: Migration
        run: supabase db push
